sudo: required
dist: trusty

before_install:
  - sudo apt-get -qq update && sudo apt-get install -y --no-install-recommends texlive-fonts-recommended texlive-latex-extra texlive-fonts-extra texlive-latex-recommended texlive-xetex lmodern texlive-pictures pgf

env:
  - TDLLANG=
  - TDLLANG=ar_AR
  - TDLLANG=be_BY
  - TDLLANG=de_DE
  - TDLLANG=en_GB
  - TDLLANG=el_EL
  - TDLLANG=es_ES
  - TDLLANG=fr_FR
  - TDLLANG=hi_IN
  - TDLLANG=id_ID
  - TDLLANG=it_IT
  - TDLLANG=ja_JP
  - TDLLANG=lt_LT
  - TDLLANG=ms_MY
  - TDLLANG=nl_NL
  - TDLLANG=pl_PL
  - TDLLANG=pt_BR
  - TDLLANG=ru_RU
  - TDLLANG=sv_SE
  - TDLLANG=tr_TR
  - TDLLANG=uk_UA
  - TDLLANG=hr_HR
  - TDLLANG=hu_HU

before_script:
  - sed -i "s/de_DE/$TDLLANG/" config.tex
  - sed -i "s/ngerman/english/" config.tex

script:
  - xelatex -interaction=nonstopmode -halt-on-error -jobname=tdl-$TDLLANG tdl.tex
  - xelatex -interaction=nonstopmode -halt-on-error -jobname=tdl-$TDLLANG tdl.tex
